### ISSUE TITLE
sendData string to android java

### ISSUE THREAD

**Issue by alex920a** [armadsen/ORSSerialPort#108]
Hello. I'm using the sendData method like this:

 NSString *string1 = @"This is string 1.";
    NSData *dataToSend = [string1 dataUsingEncoding:NSUTF8StringEncoding];
    [port sendData:dataToSend];

Now, when in android I receive the message, this has length always 64 rather than the string length itself. Do you know why?

**Comment by armadsen** [comment]
I'm afraid I don't know anything about serial port usage on Android. I have a feeling this is not something specific to ORSSerialPort.
