### ISSUE TITLE
Pd install error

### ISSUE THREAD

**Issue by smccleary** [armadsen/ORSSerialPort#146]
Im getting this error when trying to follow your instruction for Cocoapods. This is a pristine flutter app scaffold

_The platform of the target `Runner` (iOS 10.0) is not compatible with `ORSSerialPort (2.0.2)`, which does not support `ios`._

**Comment by armadsen** [comment]
ORSSerialPort is a framework for macOS, and indeed does not support iOS. Is your Flutter app for iOS or macOS? (Flutter's mostly for iOS/Android, though I understand there's some kind of early support for macOS somewhere.)

**Comment by smccleary** [comment]
Ah that explains it. Its ios. Thank you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
