### ISSUE TITLE
ORSSerial/ORSSerialPacketDescriptor.h file not found

### ISSUE THREAD

**Issue by 949699582** [armadsen/ORSSerialPort#169]
Download the code and build it! Show this error and I can not find the solution.Can someone tell me how tto deal this question?

**Comment by flemingm** [comment]
File:  ORSSerialRequest.h

//#import <ORSSerial/ORSSerialPacketDescriptor.h>
// reference framework will not find it without framework. 

# uncomment next line if not using framework. and comment out the line about.
#import "ORSSerialPacketDescriptor.h"

To build the framework using the framework project.

**Comment by armadsen** [comment]
This is fixed on master now. Please pull the latest and try again.
