### ISSUE TITLE
Does the Mac support Uart baudrate change to 3M?

### ISSUE THREAD

**Issue by yxq-Jason** [armadsen/ORSSerialPort#173]
Hi 
I post the questions in Q&A with below link.
https://github.com/armadsen/ORSSerialPort/discussions/172#discussioncomment-327040
#172 

I met a problem when test FT4232H with high speed 3M baud rate.
ORSSerial and coolTerm all not work in Mac(got nil response but works in others rates).
But I tried it same steps in windows with coolTerm, looks good with 3M baud rate communication.
It's really confused me, so is the Mac driver limited or something I missing? Has anyone tried this?

**Comment by armadsen** [comment]
I [answered](https://github.com/armadsen/ORSSerialPort/discussions/172#discussioncomment-2304996) the question over in discussions.
