### ISSUE TITLE
not compiling on OS X 10.7

### ISSUE THREAD

**Issue by azplanlos** [armadsen/ORSSerialPort#47]
not compiling on OS X 10.7 due to NS_DESIGNATED_INITIALIZER in ORSSerialPort.h as discussed in pullrequest #46 comments.

**Comment by azplanlos** [comment]
Also not compiling due to "-fobjc-arc is not supported on platforms using the legacy runtime"

**Comment by armadsen** [comment]
The legacy runtime is only for 32-bit targets. ORSSerialPort has never offered support for 32-bit targets (well, not since before I published it as open source, anyway).

**Comment by azplanlos** [comment]
but 32bit is activated as $(NATIVE_ARCH) includes 32bit on OS X 10.7. Never needed 32-bit targets anyway, but a change in the Framework Project file to 64bit Intel fixes this issue.

**Comment by azplanlos** [comment]
also compilation of Framework Project is broken due to missing linking of IOKit

**Comment by azplanlos** [comment]
and Cocoa.framwork

**Comment by armadsen** [comment]
Oh, that makes sense. I'm not opposed to changing to explicitly setting the architecture to 64-bit in the framework project. Linking IOKit and Cocoa explicitly is fine with me too. These aren't necessary in modern versions of Xcode, but they shouldn't break anything either.

**Comment by azplanlos** [comment]
yes, I think so eather. Shall I create a pull request for these changes?

**Comment by armadsen** [comment]
Sure, that would be great.

**Comment by armadsen** [comment]
Fixed by PR #48.

**Comment by azplanlos** [comment]
thanks. Just found another one… [NSArray firstObject] does not exist on 10.7. As it was included in your latest commit it was not in my fork… Just realized after merging. Changed it to equivalent [NSArray objectAtIndex:0] and compiling fine again.
