### ISSUE TITLE
How to monitor a new port is plug-in

### ISSUE THREAD

**Issue by SLboat** [armadsen/ORSSerialPort#56]
can it do that?if a plug a new serial,so it can detecting,maybe notification or delegate?

**Comment by armadsen** [comment]
Hi SLboat,

Yes, there are two ways to be notified when a new serial adapter is plugged in. You can observe the `ORSSerialPortManager`'s `availablePorts` property using Key Value Observing (KVO), or you can register for the `ORSSerialPortsWereConnectedNotification` notification posted by the serial port manager.

Both of these options are described in the top level [documentation](http://cocoadocs.org/docsets/ORSSerialPort/1.8.0/Classes/ORSSerialPortManager.html) for `ORSSerialPortManager`. You can see an [example](https://github.com/armadsen/ORSSerialPort/blob/3703b6a198109bb7cefd9fba7918f19005c08b16/Examples/ORSSerialPortDemo/Objective-C/Sources/ORSSerialPortDemoController.m#L41-L42) of registering for notifications in the ORSSerialPortDemo example project.

I hope this helps. I'm going to close this issue. If you need further assistance, comment on it and I'll reopen it, or you can [email me](mailto:andrew@openreelsoftware.com).
